Titles: Lindokhle Jonas
descripiton: A collection of data analysis projects to demonstrate various skills in data cleaning, exploration and vissualisation.
Theme: minima
Social Links: https://www.linkedin.com/in/praisworth-lindokuhle-jonas-b4b76954
