title: Lindokuhle Jonas 
description: "A collection of data analysis projects demonstrating various skills in data cleaning, exploration, and visualization."
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
social Links: https://www.linkedin.com/in/praisworth-lindokuhle-jonas-b4b76954
