titles: Lindokhle Jonas
descripiton: A collection of data analysis projects to demonstrate various skills in data cleaning, exploration and vissualisation.
theme: jekyll-theme-minimal
social Links: https://www.linkedin.com/in/praisworth-lindokuhle-jonas-b4b76954
