title: Lindokuhle Jonas 
#description: "A collection of data analysis projects demonstrating various skills in data cleaning, exploration, and visualization."
remote_theme: "jekyll/time machine"
plugins:
  - jekyll-feed
social Links: https://www.linkedin.com/in/praisworth-lindokuhle-jonas-b4b76954
